[phases.setup]
nixPkgs = ['nodejs_20']
aptPkgs = []

[phases.install]
cmds = [
  'npm install -g pnpm@10.18.2 && pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['cd apps/web && pnpm build']

[start]
cmd = 'cd apps/web && pnpm start'
