[phases.setup]
nixPkgs = ['nodejs_20']
aptPkgs = []

[phases.install]
cmds = [
  'npm install -g pnpm@10.18.2',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm --filter @congo-gaming/web build']

[start]
cmd = 'pnpm --filter @congo-gaming/web start'
